/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../common.js"
  import type { MockAttestcoinQueryVerifier, MockAttestcoinQueryVerifierInterface } from "../../test/MockAttestcoinQueryVerifier.js";

  const _abi = [
  {
    "inputs": [
      {
        "components": [
          {
            "internalType": "bytes32",
            "name": "root",
            "type": "bytes32"
          },
          {
            "components": [
              {
                "internalType": "bytes32",
                "name": "hash",
                "type": "bytes32"
              },
              {
                "internalType": "bool",
                "name": "isLeft",
                "type": "bool"
              }
            ],
            "internalType": "struct IAttestcoinQueryVerifier.MerkleProofEntry[]",
            "name": "siblings",
            "type": "tuple[]"
          }
        ],
        "internalType": "struct IAttestcoinQueryVerifier.MerkleProof",
        "name": "",
        "type": "tuple"
      }
    ],
    "name": "calculateTxIndex",
    "outputs": [
      {
        "internalType": "uint64",
        "name": "",
        "type": "uint64"
      }
    ],
    "stateMutability": "pure",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint64",
        "name": "",
        "type": "uint64"
      },
      {
        "internalType": "uint64[]",
        "name": "heights",
        "type": "uint64[]"
      },
      {
        "internalType": "bytes[]",
        "name": "encodedTransactions",
        "type": "bytes[]"
      },
      {
        "components": [
          {
            "internalType": "bytes32",
            "name": "root",
            "type": "bytes32"
          },
          {
            "components": [
              {
                "internalType": "bytes32",
                "name": "hash",
                "type": "bytes32"
              },
              {
                "internalType": "bool",
                "name": "isLeft",
                "type": "bool"
              }
            ],
            "internalType": "struct IAttestcoinQueryVerifier.MerkleProofEntry[]",
            "name": "siblings",
            "type": "tuple[]"
          }
        ],
        "internalType": "struct IAttestcoinQueryVerifier.MerkleProof[]",
        "name": "merkleProofs",
        "type": "tuple[]"
      },
      {
        "components": [
          {
            "internalType": "bytes32",
            "name": "lowerEndpointDigest",
            "type": "bytes32"
          },
          {
            "internalType": "bytes32[]",
            "name": "roots",
            "type": "bytes32[]"
          }
        ],
        "internalType": "struct IAttestcoinQueryVerifier.ContinuityProof",
        "name": "",
        "type": "tuple"
      }
    ],
    "name": "verify",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "pure",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint64",
        "name": "",
        "type": "uint64"
      },
      {
        "internalType": "uint64",
        "name": "",
        "type": "uint64"
      },
      {
        "internalType": "bytes",
        "name": "",
        "type": "bytes"
      },
      {
        "components": [
          {
            "internalType": "bytes32",
            "name": "root",
            "type": "bytes32"
          },
          {
            "components": [
              {
                "internalType": "bytes32",
                "name": "hash",
                "type": "bytes32"
              },
              {
                "internalType": "bool",
                "name": "isLeft",
                "type": "bool"
              }
            ],
            "internalType": "struct IAttestcoinQueryVerifier.MerkleProofEntry[]",
            "name": "siblings",
            "type": "tuple[]"
          }
        ],
        "internalType": "struct IAttestcoinQueryVerifier.MerkleProof",
        "name": "merkleProof",
        "type": "tuple"
      },
      {
        "components": [
          {
            "internalType": "bytes32",
            "name": "lowerEndpointDigest",
            "type": "bytes32"
          },
          {
            "internalType": "bytes32[]",
            "name": "roots",
            "type": "bytes32[]"
          }
        ],
        "internalType": "struct IAttestcoinQueryVerifier.ContinuityProof",
        "name": "",
        "type": "tuple"
      }
    ],
    "name": "verify",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "pure",
    "type": "function"
  }
] as const;

  const _bytecode = "0x608080604052346015576102e0908161001a8239f35b5f80fdfe60806040526004361015610011575f80fd5b5f3560e01c80631b5f6f881461012e57806344f85f1c146100f157637cc4e2581461003a575f80fd5b346100ed5760a03660031901126100ed576100536101e4565b5061005c6101fb565b5060443567ffffffffffffffff81116100ed57366023820112156100ed57806004013567ffffffffffffffff81116100ed57369101602401116100ed5760643567ffffffffffffffff81116100ed57604060031982360301126100ed5760843567ffffffffffffffff81116100ed5760409060031990360301126100ed576020906001604051916004013514158152f35b5f80fd5b346100ed5760203660031901126100ed5760043567ffffffffffffffff81116100ed5760409060031990360301126100ed57602060405160588152f35b346100ed5760a03660031901126100ed576101476101e4565b5060243567ffffffffffffffff81116100ed57610168903690600401610212565b9060443567ffffffffffffffff81116100ed57610189903690600401610212565b9060643567ffffffffffffffff81116100ed576101aa903690600401610212565b92909160843567ffffffffffffffff81116100ed5760409060031990360301126100ed576020956101da95610243565b6040519015158152f35b6004359067ffffffffffffffff821682036100ed57565b6024359067ffffffffffffffff821682036100ed57565b9181601f840112156100ed5782359167ffffffffffffffff83116100ed576020808501948460051b0101116100ed57565b509184915082149182159261029f575b5050610299575f5b82811015610291578060051b820135603e19833603018112156100ed5782013560011461028a5760010161025b565b5050505f90565b505050600190565b50505f90565b14159050825f61025356fea264697066735822122097e926b853563601b038d9e28c033ba60675b780d8da0f7e0826a08ea33815b764736f6c634300081c0033";

  
      type MockAttestcoinQueryVerifierConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: MockAttestcoinQueryVerifierConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class MockAttestcoinQueryVerifier__factory extends ContractFactory {
    
      constructor(...args: MockAttestcoinQueryVerifierConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<MockAttestcoinQueryVerifier & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): MockAttestcoinQueryVerifier__factory {
      return super.connect(runner) as MockAttestcoinQueryVerifier__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): MockAttestcoinQueryVerifierInterface {
      return new Interface(_abi) as MockAttestcoinQueryVerifierInterface;
    }
    
    override attach(address: string | Addressable): MockAttestcoinQueryVerifier {
      return super.attach(address) as MockAttestcoinQueryVerifier;
    }
  static connect(address: string, runner?: ContractRunner | null): MockAttestcoinQueryVerifier {
      return new Contract(address, _abi, runner) as unknown as MockAttestcoinQueryVerifier;
    }
  }

  
  