/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../common.js"
  import type { MockAttestcoinQueryVerifier, MockAttestcoinQueryVerifierInterface } from "../../test/MockAttestcoinQueryVerifier.js";

  const _abi = [
  {
    "inputs": [
      {
        "components": [
          {
            "internalType": "bytes32",
            "name": "root",
            "type": "bytes32"
          },
          {
            "components": [
              {
                "internalType": "bytes32",
                "name": "hash",
                "type": "bytes32"
              },
              {
                "internalType": "bool",
                "name": "isLeft",
                "type": "bool"
              }
            ],
            "internalType": "struct IAttestcoinQueryVerifier.MerkleProofEntry[]",
            "name": "siblings",
            "type": "tuple[]"
          }
        ],
        "internalType": "struct IAttestcoinQueryVerifier.MerkleProof",
        "name": "",
        "type": "tuple"
      }
    ],
    "name": "calculateTxIndex",
    "outputs": [
      {
        "internalType": "uint64",
        "name": "",
        "type": "uint64"
      }
    ],
    "stateMutability": "pure",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint64",
        "name": "",
        "type": "uint64"
      },
      {
        "internalType": "uint64",
        "name": "",
        "type": "uint64"
      },
      {
        "internalType": "bytes",
        "name": "",
        "type": "bytes"
      },
      {
        "components": [
          {
            "internalType": "bytes32",
            "name": "root",
            "type": "bytes32"
          },
          {
            "components": [
              {
                "internalType": "bytes32",
                "name": "hash",
                "type": "bytes32"
              },
              {
                "internalType": "bool",
                "name": "isLeft",
                "type": "bool"
              }
            ],
            "internalType": "struct IAttestcoinQueryVerifier.MerkleProofEntry[]",
            "name": "siblings",
            "type": "tuple[]"
          }
        ],
        "internalType": "struct IAttestcoinQueryVerifier.MerkleProof",
        "name": "merkleProof",
        "type": "tuple"
      },
      {
        "components": [
          {
            "internalType": "bytes32",
            "name": "lowerEndpointDigest",
            "type": "bytes32"
          },
          {
            "internalType": "bytes32[]",
            "name": "roots",
            "type": "bytes32[]"
          }
        ],
        "internalType": "struct IAttestcoinQueryVerifier.ContinuityProof",
        "name": "",
        "type": "tuple"
      }
    ],
    "name": "verify",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "pure",
    "type": "function"
  }
] as const;

  const _bytecode = "0x60808060405234601557610188908161001a8239f35b5f80fdfe6080806040526004361015610012575f80fd5b5f3560e01c90816344f85f1c146100e95750637cc4e25814610032575f80fd5b346100e55760a03660031901126100e55761004b610124565b5061005461013b565b5060443567ffffffffffffffff81116100e557366023820112156100e557806004013567ffffffffffffffff81116100e557369101602401116100e55760643567ffffffffffffffff81116100e557604060031982360301126100e55760843567ffffffffffffffff81116100e55760409060031990360301126100e5576020906001604051916004013514158152f35b5f80fd5b346100e55760203660031901126100e55760043567ffffffffffffffff81116100e55760409060031990360301126100e55780605860209252f35b6004359067ffffffffffffffff821682036100e557565b6024359067ffffffffffffffff821682036100e55756fea26469706673582212207d83a120f8edab85743691fc250b4d40c8a4ed62813eed1f232129b91d0d73df64736f6c634300081c0033";

  
      type MockAttestcoinQueryVerifierConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: MockAttestcoinQueryVerifierConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class MockAttestcoinQueryVerifier__factory extends ContractFactory {
    
      constructor(...args: MockAttestcoinQueryVerifierConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<MockAttestcoinQueryVerifier & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): MockAttestcoinQueryVerifier__factory {
      return super.connect(runner) as MockAttestcoinQueryVerifier__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): MockAttestcoinQueryVerifierInterface {
      return new Interface(_abi) as MockAttestcoinQueryVerifierInterface;
    }
    
    override attach(address: string | Addressable): MockAttestcoinQueryVerifier {
      return super.attach(address) as MockAttestcoinQueryVerifier;
    }
  static connect(address: string, runner?: ContractRunner | null): MockAttestcoinQueryVerifier {
      return new Contract(address, _abi, runner) as unknown as MockAttestcoinQueryVerifier;
    }
  }

  
  