/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface ExecutionReporterInterface extends Interface {
    getFunction(nameOrSignature: "reportExecution"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AgentExecutionRecorded"): EventFragment;

    encodeFunctionData(functionFragment: 'reportExecution', values: [AddressLike, BytesLike, boolean, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'reportExecution', data: BytesLike): Result;
  }

  
    export namespace AgentExecutionRecordedEvent {
      export type InputTuple = [agent: AddressLike, executionId: BytesLike, success: boolean, volume: BigNumberish, timestamp: BigNumberish];
      export type OutputTuple = [agent: string, executionId: string, success: boolean, volume: bigint, timestamp: bigint];
      export interface OutputObject {agent: string, executionId: string, success: boolean, volume: bigint, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface ExecutionReporter extends BaseContract {
    
    connect(runner?: ContractRunner | null): ExecutionReporter;
    waitForDeployment(): Promise<this>;

    interface: ExecutionReporterInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    reportExecution: TypedContractMethod<
      [agent: AddressLike, executionId: BytesLike, success: boolean, volume: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'reportExecution'): TypedContractMethod<
      [agent: AddressLike, executionId: BytesLike, success: boolean, volume: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'AgentExecutionRecorded'): TypedContractEvent<AgentExecutionRecordedEvent.InputTuple, AgentExecutionRecordedEvent.OutputTuple, AgentExecutionRecordedEvent.OutputObject>;

    filters: {
      
      'AgentExecutionRecorded(address,bytes32,bool,uint256,uint256)': TypedContractEvent<AgentExecutionRecordedEvent.InputTuple, AgentExecutionRecordedEvent.OutputTuple, AgentExecutionRecordedEvent.OutputObject>;
      AgentExecutionRecorded: TypedContractEvent<AgentExecutionRecordedEvent.InputTuple, AgentExecutionRecordedEvent.OutputTuple, AgentExecutionRecordedEvent.OutputObject>;
    
    };
  }