/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'ExecutionReporter', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ExecutionReporter__factory>
getContractFactory(name: 'MaatCore', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MaatCore__factory>
getContractFactory(name: 'InvoiceRegistry', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.InvoiceRegistry__factory>
getContractFactory(name: 'MaatCreditPolicy', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MaatCreditPolicy__factory>
getContractFactory(name: 'MaatPolicy', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MaatPolicy__factory>
getContractFactory(name: 'MaatSettlementVerifier', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MaatSettlementVerifier__factory>
getContractFactory(name: 'INativeQueryVerifier', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.INativeQueryVerifier__factory>
getContractFactory(name: 'MaatVerifier', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MaatVerifier__factory>
getContractFactory(name: 'MaatTrustRegistry', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MaatTrustRegistry__factory>
getContractFactory(name: 'SettlementRouter', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.SettlementRouter__factory>
getContractFactory(name: 'IAttestcoinQueryVerifier', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IAttestcoinQueryVerifier__factory>
getContractFactory(name: 'AttestedExecutionDecoderHarness', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.AttestedExecutionDecoderHarness__factory>
getContractFactory(name: 'AttestedPaymentDecoderHarness', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.AttestedPaymentDecoderHarness__factory>
getContractFactory(name: 'MockAttestcoinQueryVerifier', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockAttestcoinQueryVerifier__factory>
getContractFactory(name: 'MockUSDC', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockUSDC__factory>

  getContractAt(name: 'ExecutionReporter', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ExecutionReporter>
getContractAt(name: 'MaatCore', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MaatCore>
getContractAt(name: 'InvoiceRegistry', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.InvoiceRegistry>
getContractAt(name: 'MaatCreditPolicy', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MaatCreditPolicy>
getContractAt(name: 'MaatPolicy', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MaatPolicy>
getContractAt(name: 'MaatSettlementVerifier', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MaatSettlementVerifier>
getContractAt(name: 'INativeQueryVerifier', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.INativeQueryVerifier>
getContractAt(name: 'MaatVerifier', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MaatVerifier>
getContractAt(name: 'MaatTrustRegistry', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MaatTrustRegistry>
getContractAt(name: 'SettlementRouter', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.SettlementRouter>
getContractAt(name: 'IAttestcoinQueryVerifier', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IAttestcoinQueryVerifier>
getContractAt(name: 'AttestedExecutionDecoderHarness', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.AttestedExecutionDecoderHarness>
getContractAt(name: 'AttestedPaymentDecoderHarness', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.AttestedPaymentDecoderHarness>
getContractAt(name: 'MockAttestcoinQueryVerifier', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockAttestcoinQueryVerifier>
getContractAt(name: 'MockUSDC', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockUSDC>

  deployContract(name: 'ExecutionReporter', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ExecutionReporter>
deployContract(name: 'MaatCore', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MaatCore>
deployContract(name: 'InvoiceRegistry', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.InvoiceRegistry>
deployContract(name: 'MaatCreditPolicy', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MaatCreditPolicy>
deployContract(name: 'MaatPolicy', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MaatPolicy>
deployContract(name: 'MaatSettlementVerifier', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MaatSettlementVerifier>
deployContract(name: 'INativeQueryVerifier', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.INativeQueryVerifier>
deployContract(name: 'MaatVerifier', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MaatVerifier>
deployContract(name: 'MaatTrustRegistry', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MaatTrustRegistry>
deployContract(name: 'SettlementRouter', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SettlementRouter>
deployContract(name: 'IAttestcoinQueryVerifier', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IAttestcoinQueryVerifier>
deployContract(name: 'AttestedExecutionDecoderHarness', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.AttestedExecutionDecoderHarness>
deployContract(name: 'AttestedPaymentDecoderHarness', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.AttestedPaymentDecoderHarness>
deployContract(name: 'MockAttestcoinQueryVerifier', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockAttestcoinQueryVerifier>
deployContract(name: 'MockUSDC', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockUSDC>

  deployContract(name: 'ExecutionReporter', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ExecutionReporter>
deployContract(name: 'MaatCore', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MaatCore>
deployContract(name: 'InvoiceRegistry', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.InvoiceRegistry>
deployContract(name: 'MaatCreditPolicy', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MaatCreditPolicy>
deployContract(name: 'MaatPolicy', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MaatPolicy>
deployContract(name: 'MaatSettlementVerifier', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MaatSettlementVerifier>
deployContract(name: 'INativeQueryVerifier', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.INativeQueryVerifier>
deployContract(name: 'MaatVerifier', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MaatVerifier>
deployContract(name: 'MaatTrustRegistry', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MaatTrustRegistry>
deployContract(name: 'SettlementRouter', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SettlementRouter>
deployContract(name: 'IAttestcoinQueryVerifier', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IAttestcoinQueryVerifier>
deployContract(name: 'AttestedExecutionDecoderHarness', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.AttestedExecutionDecoderHarness>
deployContract(name: 'AttestedPaymentDecoderHarness', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.AttestedPaymentDecoderHarness>
deployContract(name: 'MockAttestcoinQueryVerifier', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockAttestcoinQueryVerifier>
deployContract(name: 'MockUSDC', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockUSDC>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  