/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace InvoiceRegistry {
      
    export type InvoiceStruct = {vendor: AddressLike, buyer: AddressLike, amount: BigNumberish, issuedAt: BigNumberish, dueAt: BigNumberish, settledAt: BigNumberish, metadataHash: BytesLike, status: BigNumberish}

    export type InvoiceStructOutput = [vendor: string, buyer: string, amount: bigint, issuedAt: bigint, dueAt: bigint, settledAt: bigint, metadataHash: string, status: bigint] & {vendor: string, buyer: string, amount: bigint, issuedAt: bigint, dueAt: bigint, settledAt: bigint, metadataHash: string, status: bigint }
  
    }

  export interface InvoiceRegistryInterface extends Interface {
    getFunction(nameOrSignature: "cancelInvoice" | "createInvoice" | "getInvoice" | "setSettlementVerifier" | "settleVerifiedPayment" | "settlementVerifier" | "vendorNonces"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "InvoiceCancelled" | "InvoiceCreated" | "InvoiceSettled" | "SettlementVerifierUpdated"): EventFragment;

    encodeFunctionData(functionFragment: 'cancelInvoice', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'createInvoice', values: [AddressLike, BigNumberish, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'getInvoice', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'setSettlementVerifier', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'settleVerifiedPayment', values: [BytesLike, AddressLike, AddressLike, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'settlementVerifier', values?: undefined): string;
encodeFunctionData(functionFragment: 'vendorNonces', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'cancelInvoice', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createInvoice', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getInvoice', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setSettlementVerifier', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'settleVerifiedPayment', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'settlementVerifier', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'vendorNonces', data: BytesLike): Result;
  }

  
    export namespace InvoiceCancelledEvent {
      export type InputTuple = [invoiceId: BytesLike, vendor: AddressLike];
      export type OutputTuple = [invoiceId: string, vendor: string];
      export interface OutputObject {invoiceId: string, vendor: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace InvoiceCreatedEvent {
      export type InputTuple = [invoiceId: BytesLike, vendor: AddressLike, buyer: AddressLike, amount: BigNumberish, issuedAt: BigNumberish, dueAt: BigNumberish, metadataHash: BytesLike];
      export type OutputTuple = [invoiceId: string, vendor: string, buyer: string, amount: bigint, issuedAt: bigint, dueAt: bigint, metadataHash: string];
      export interface OutputObject {invoiceId: string, vendor: string, buyer: string, amount: bigint, issuedAt: bigint, dueAt: bigint, metadataHash: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace InvoiceSettledEvent {
      export type InputTuple = [invoiceId: BytesLike, payer: AddressLike, vendor: AddressLike, amount: BigNumberish, paidAt: BigNumberish, onTime: boolean];
      export type OutputTuple = [invoiceId: string, payer: string, vendor: string, amount: bigint, paidAt: bigint, onTime: boolean];
      export interface OutputObject {invoiceId: string, payer: string, vendor: string, amount: bigint, paidAt: bigint, onTime: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SettlementVerifierUpdatedEvent {
      export type InputTuple = [previousVerifier: AddressLike, newVerifier: AddressLike];
      export type OutputTuple = [previousVerifier: string, newVerifier: string];
      export interface OutputObject {previousVerifier: string, newVerifier: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface InvoiceRegistry extends BaseContract {
    
    connect(runner?: ContractRunner | null): InvoiceRegistry;
    waitForDeployment(): Promise<this>;

    interface: InvoiceRegistryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    cancelInvoice: TypedContractMethod<
      [invoiceId: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    createInvoice: TypedContractMethod<
      [buyer: AddressLike, amount: BigNumberish, dueAt: BigNumberish, metadataHash: BytesLike, ],
      [string],
      'nonpayable'
    >
    

    
    getInvoice: TypedContractMethod<
      [invoiceId: BytesLike, ],
      [InvoiceRegistry.InvoiceStructOutput],
      'view'
    >
    

    
    setSettlementVerifier: TypedContractMethod<
      [newVerifier: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    settleVerifiedPayment: TypedContractMethod<
      [invoiceId: BytesLike, payer: AddressLike, vendor: AddressLike, amount: BigNumberish, paidAt: BigNumberish, ],
      [boolean],
      'nonpayable'
    >
    

    
    settlementVerifier: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    vendorNonces: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'cancelInvoice'): TypedContractMethod<
      [invoiceId: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createInvoice'): TypedContractMethod<
      [buyer: AddressLike, amount: BigNumberish, dueAt: BigNumberish, metadataHash: BytesLike, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getInvoice'): TypedContractMethod<
      [invoiceId: BytesLike, ],
      [InvoiceRegistry.InvoiceStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'setSettlementVerifier'): TypedContractMethod<
      [newVerifier: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'settleVerifiedPayment'): TypedContractMethod<
      [invoiceId: BytesLike, payer: AddressLike, vendor: AddressLike, amount: BigNumberish, paidAt: BigNumberish, ],
      [boolean],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'settlementVerifier'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'vendorNonces'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;

    getEvent(key: 'InvoiceCancelled'): TypedContractEvent<InvoiceCancelledEvent.InputTuple, InvoiceCancelledEvent.OutputTuple, InvoiceCancelledEvent.OutputObject>;
getEvent(key: 'InvoiceCreated'): TypedContractEvent<InvoiceCreatedEvent.InputTuple, InvoiceCreatedEvent.OutputTuple, InvoiceCreatedEvent.OutputObject>;
getEvent(key: 'InvoiceSettled'): TypedContractEvent<InvoiceSettledEvent.InputTuple, InvoiceSettledEvent.OutputTuple, InvoiceSettledEvent.OutputObject>;
getEvent(key: 'SettlementVerifierUpdated'): TypedContractEvent<SettlementVerifierUpdatedEvent.InputTuple, SettlementVerifierUpdatedEvent.OutputTuple, SettlementVerifierUpdatedEvent.OutputObject>;

    filters: {
      
      'InvoiceCancelled(bytes32,address)': TypedContractEvent<InvoiceCancelledEvent.InputTuple, InvoiceCancelledEvent.OutputTuple, InvoiceCancelledEvent.OutputObject>;
      InvoiceCancelled: TypedContractEvent<InvoiceCancelledEvent.InputTuple, InvoiceCancelledEvent.OutputTuple, InvoiceCancelledEvent.OutputObject>;
    

      'InvoiceCreated(bytes32,address,address,uint256,uint256,uint256,bytes32)': TypedContractEvent<InvoiceCreatedEvent.InputTuple, InvoiceCreatedEvent.OutputTuple, InvoiceCreatedEvent.OutputObject>;
      InvoiceCreated: TypedContractEvent<InvoiceCreatedEvent.InputTuple, InvoiceCreatedEvent.OutputTuple, InvoiceCreatedEvent.OutputObject>;
    

      'InvoiceSettled(bytes32,address,address,uint256,uint256,bool)': TypedContractEvent<InvoiceSettledEvent.InputTuple, InvoiceSettledEvent.OutputTuple, InvoiceSettledEvent.OutputObject>;
      InvoiceSettled: TypedContractEvent<InvoiceSettledEvent.InputTuple, InvoiceSettledEvent.OutputTuple, InvoiceSettledEvent.OutputObject>;
    

      'SettlementVerifierUpdated(address,address)': TypedContractEvent<SettlementVerifierUpdatedEvent.InputTuple, SettlementVerifierUpdatedEvent.OutputTuple, SettlementVerifierUpdatedEvent.OutputObject>;
      SettlementVerifierUpdated: TypedContractEvent<SettlementVerifierUpdatedEvent.InputTuple, SettlementVerifierUpdatedEvent.OutputTuple, SettlementVerifierUpdatedEvent.OutputObject>;
    
    };
  }