/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace MaatCore {
      
    export type AgentMetricsStruct = {executionCount: BigNumberish, successCount: BigNumberish, totalVolume: BigNumberish, lastSeenAt: BigNumberish, tier: BigNumberish}

    export type AgentMetricsStructOutput = [executionCount: bigint, successCount: bigint, totalVolume: bigint, lastSeenAt: bigint, tier: bigint] & {executionCount: bigint, successCount: bigint, totalVolume: bigint, lastSeenAt: bigint, tier: bigint }
  
    }

  export interface MaatCoreInterface extends Interface {
    getFunction(nameOrSignature: "getMetrics" | "processedExecutionIds" | "recordVerifiedExecution" | "setVerifier" | "tierOf" | "verifier"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AgentMetricsUpdated"): EventFragment;

    encodeFunctionData(functionFragment: 'getMetrics', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'processedExecutionIds', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'recordVerifiedExecution', values: [AddressLike, BytesLike, boolean, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'setVerifier', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'tierOf', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'verifier', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'getMetrics', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'processedExecutionIds', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'recordVerifiedExecution', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setVerifier', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tierOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'verifier', data: BytesLike): Result;
  }

  
    export namespace AgentMetricsUpdatedEvent {
      export type InputTuple = [agent: AddressLike, executionId: BytesLike, executionCount: BigNumberish, successCount: BigNumberish, totalVolume: BigNumberish, lastSeenAt: BigNumberish, tier: BigNumberish];
      export type OutputTuple = [agent: string, executionId: string, executionCount: bigint, successCount: bigint, totalVolume: bigint, lastSeenAt: bigint, tier: bigint];
      export interface OutputObject {agent: string, executionId: string, executionCount: bigint, successCount: bigint, totalVolume: bigint, lastSeenAt: bigint, tier: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface MaatCore extends BaseContract {
    
    connect(runner?: ContractRunner | null): MaatCore;
    waitForDeployment(): Promise<this>;

    interface: MaatCoreInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    getMetrics: TypedContractMethod<
      [agent: AddressLike, ],
      [MaatCore.AgentMetricsStructOutput],
      'view'
    >
    

    
    processedExecutionIds: TypedContractMethod<
      [arg0: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    recordVerifiedExecution: TypedContractMethod<
      [agent: AddressLike, executionId: BytesLike, success: boolean, volume: BigNumberish, observedAt: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setVerifier: TypedContractMethod<
      [newVerifier: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    tierOf: TypedContractMethod<
      [agent: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    verifier: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'getMetrics'): TypedContractMethod<
      [agent: AddressLike, ],
      [MaatCore.AgentMetricsStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'processedExecutionIds'): TypedContractMethod<
      [arg0: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'recordVerifiedExecution'): TypedContractMethod<
      [agent: AddressLike, executionId: BytesLike, success: boolean, volume: BigNumberish, observedAt: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setVerifier'): TypedContractMethod<
      [newVerifier: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'tierOf'): TypedContractMethod<
      [agent: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'verifier'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    getEvent(key: 'AgentMetricsUpdated'): TypedContractEvent<AgentMetricsUpdatedEvent.InputTuple, AgentMetricsUpdatedEvent.OutputTuple, AgentMetricsUpdatedEvent.OutputObject>;

    filters: {
      
      'AgentMetricsUpdated(address,bytes32,uint256,uint256,uint256,uint256,uint8)': TypedContractEvent<AgentMetricsUpdatedEvent.InputTuple, AgentMetricsUpdatedEvent.OutputTuple, AgentMetricsUpdatedEvent.OutputObject>;
      AgentMetricsUpdated: TypedContractEvent<AgentMetricsUpdatedEvent.InputTuple, AgentMetricsUpdatedEvent.OutputTuple, AgentMetricsUpdatedEvent.OutputObject>;
    
    };
  }