/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface MaatCreditPolicyInterface extends Interface {
    getFunction(nameOrSignature: "BRONZE_LIMIT_USDC" | "GOLD_LIMIT_USDC" | "SILVER_LIMIT_USDC" | "canExtendTerms" | "creditLimitUsdc" | "trustRegistry"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'BRONZE_LIMIT_USDC', values?: undefined): string;
encodeFunctionData(functionFragment: 'GOLD_LIMIT_USDC', values?: undefined): string;
encodeFunctionData(functionFragment: 'SILVER_LIMIT_USDC', values?: undefined): string;
encodeFunctionData(functionFragment: 'canExtendTerms', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'creditLimitUsdc', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'trustRegistry', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'BRONZE_LIMIT_USDC', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'GOLD_LIMIT_USDC', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'SILVER_LIMIT_USDC', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'canExtendTerms', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'creditLimitUsdc', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'trustRegistry', data: BytesLike): Result;
  }

  

  export interface MaatCreditPolicy extends BaseContract {
    
    connect(runner?: ContractRunner | null): MaatCreditPolicy;
    waitForDeployment(): Promise<this>;

    interface: MaatCreditPolicyInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    BRONZE_LIMIT_USDC: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    GOLD_LIMIT_USDC: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    SILVER_LIMIT_USDC: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    canExtendTerms: TypedContractMethod<
      [payer: AddressLike, invoiceAmount: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    creditLimitUsdc: TypedContractMethod<
      [payer: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    trustRegistry: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'BRONZE_LIMIT_USDC'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'GOLD_LIMIT_USDC'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'SILVER_LIMIT_USDC'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'canExtendTerms'): TypedContractMethod<
      [payer: AddressLike, invoiceAmount: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'creditLimitUsdc'): TypedContractMethod<
      [payer: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'trustRegistry'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    

    filters: {
      
    };
  }