/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface MaatPolicyInterface extends Interface {
    getFunction(nameOrSignature: "canOperate" | "delegationCap" | "maatCore"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'canOperate', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'delegationCap', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'maatCore', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'canOperate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'delegationCap', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'maatCore', data: BytesLike): Result;
  }

  

  export interface MaatPolicy extends BaseContract {
    
    connect(runner?: ContractRunner | null): MaatPolicy;
    waitForDeployment(): Promise<this>;

    interface: MaatPolicyInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    canOperate: TypedContractMethod<
      [agent: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    delegationCap: TypedContractMethod<
      [agent: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    maatCore: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'canOperate'): TypedContractMethod<
      [agent: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'delegationCap'): TypedContractMethod<
      [agent: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'maatCore'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    

    filters: {
      
    };
  }