/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace IAttestcoinQueryVerifier {
      
    export type MerkleProofEntryStruct = {hash: BytesLike, isLeft: boolean}

    export type MerkleProofEntryStructOutput = [hash: string, isLeft: boolean] & {hash: string, isLeft: boolean }
  

    export type MerkleProofStruct = {root: BytesLike, siblings: IAttestcoinQueryVerifier.MerkleProofEntryStruct[]}

    export type MerkleProofStructOutput = [root: string, siblings: IAttestcoinQueryVerifier.MerkleProofEntryStructOutput[]] & {root: string, siblings: IAttestcoinQueryVerifier.MerkleProofEntryStructOutput[] }
  

    export type ContinuityProofStruct = {lowerEndpointDigest: BytesLike, roots: BytesLike[]}

    export type ContinuityProofStructOutput = [lowerEndpointDigest: string, roots: string[]] & {lowerEndpointDigest: string, roots: string[] }
  
    }

  export interface MaatSettlementVerifierInterface extends Interface {
    getFunction(nameOrSignature: "VERIFIER" | "invoiceRegistry" | "processedQueries" | "sourceChainKey" | "sourceRouter" | "submitVerifiedSettlement" | "trustRegistry"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "SettlementProofAccepted"): EventFragment;

    encodeFunctionData(functionFragment: 'VERIFIER', values?: undefined): string;
encodeFunctionData(functionFragment: 'invoiceRegistry', values?: undefined): string;
encodeFunctionData(functionFragment: 'processedQueries', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'sourceChainKey', values?: undefined): string;
encodeFunctionData(functionFragment: 'sourceRouter', values?: undefined): string;
encodeFunctionData(functionFragment: 'submitVerifiedSettlement', values: [BigNumberish, BigNumberish, BytesLike, IAttestcoinQueryVerifier.MerkleProofStruct, IAttestcoinQueryVerifier.ContinuityProofStruct]): string;
encodeFunctionData(functionFragment: 'trustRegistry', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'VERIFIER', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'invoiceRegistry', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'processedQueries', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'sourceChainKey', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'sourceRouter', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'submitVerifiedSettlement', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'trustRegistry', data: BytesLike): Result;
  }

  
    export namespace SettlementProofAcceptedEvent {
      export type InputTuple = [chainKey: BigNumberish, height: BigNumberish, txIndex: BigNumberish, invoiceId: BytesLike, payer: AddressLike, vendor: AddressLike, amount: BigNumberish, paidAt: BigNumberish, onTime: boolean];
      export type OutputTuple = [chainKey: bigint, height: bigint, txIndex: bigint, invoiceId: string, payer: string, vendor: string, amount: bigint, paidAt: bigint, onTime: boolean];
      export interface OutputObject {chainKey: bigint, height: bigint, txIndex: bigint, invoiceId: string, payer: string, vendor: string, amount: bigint, paidAt: bigint, onTime: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface MaatSettlementVerifier extends BaseContract {
    
    connect(runner?: ContractRunner | null): MaatSettlementVerifier;
    waitForDeployment(): Promise<this>;

    interface: MaatSettlementVerifierInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    VERIFIER: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    invoiceRegistry: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    processedQueries: TypedContractMethod<
      [arg0: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    sourceChainKey: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    sourceRouter: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    submitVerifiedSettlement: TypedContractMethod<
      [chainKey: BigNumberish, height: BigNumberish, encodedTransaction: BytesLike, merkleProof: IAttestcoinQueryVerifier.MerkleProofStruct, continuityProof: IAttestcoinQueryVerifier.ContinuityProofStruct, ],
      [boolean],
      'nonpayable'
    >
    

    
    trustRegistry: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'VERIFIER'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'invoiceRegistry'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'processedQueries'): TypedContractMethod<
      [arg0: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'sourceChainKey'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'sourceRouter'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'submitVerifiedSettlement'): TypedContractMethod<
      [chainKey: BigNumberish, height: BigNumberish, encodedTransaction: BytesLike, merkleProof: IAttestcoinQueryVerifier.MerkleProofStruct, continuityProof: IAttestcoinQueryVerifier.ContinuityProofStruct, ],
      [boolean],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'trustRegistry'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    getEvent(key: 'SettlementProofAccepted'): TypedContractEvent<SettlementProofAcceptedEvent.InputTuple, SettlementProofAcceptedEvent.OutputTuple, SettlementProofAcceptedEvent.OutputObject>;

    filters: {
      
      'SettlementProofAccepted(uint64,uint64,uint64,bytes32,address,address,uint256,uint256,bool)': TypedContractEvent<SettlementProofAcceptedEvent.InputTuple, SettlementProofAcceptedEvent.OutputTuple, SettlementProofAcceptedEvent.OutputObject>;
      SettlementProofAccepted: TypedContractEvent<SettlementProofAcceptedEvent.InputTuple, SettlementProofAcceptedEvent.OutputTuple, SettlementProofAcceptedEvent.OutputObject>;
    
    };
  }