/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace MaatTrustRegistry {
      
    export type PayerMetricsStruct = {settledInvoiceCount: BigNumberish, onTimeSettlementCount: BigNumberish, lateSettlementCount: BigNumberish, lastSettledAt: BigNumberish, totalPaidUsdc: BigNumberish, tier: BigNumberish}

    export type PayerMetricsStructOutput = [settledInvoiceCount: bigint, onTimeSettlementCount: bigint, lateSettlementCount: bigint, lastSettledAt: bigint, totalPaidUsdc: bigint, tier: bigint] & {settledInvoiceCount: bigint, onTimeSettlementCount: bigint, lateSettlementCount: bigint, lastSettledAt: bigint, totalPaidUsdc: bigint, tier: bigint }
  

    export type VendorMetricsStruct = {settledInvoiceCount: BigNumberish, lastSettledAt: BigNumberish, totalReceivedUsdc: BigNumberish}

    export type VendorMetricsStructOutput = [settledInvoiceCount: bigint, lastSettledAt: bigint, totalReceivedUsdc: bigint] & {settledInvoiceCount: bigint, lastSettledAt: bigint, totalReceivedUsdc: bigint }
  
    }

  export interface MaatTrustRegistryInterface extends Interface {
    getFunction(nameOrSignature: "getPayerMetrics" | "getVendorMetrics" | "processedInvoiceIds" | "recordVerifiedSettlement" | "setSettlementVerifier" | "settlementVerifier" | "tierOf"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "PayerTrustUpdated" | "SettlementVerifierUpdated" | "VendorActivityUpdated"): EventFragment;

    encodeFunctionData(functionFragment: 'getPayerMetrics', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getVendorMetrics', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'processedInvoiceIds', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'recordVerifiedSettlement', values: [BytesLike, AddressLike, AddressLike, BigNumberish, BigNumberish, boolean]): string;
encodeFunctionData(functionFragment: 'setSettlementVerifier', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'settlementVerifier', values?: undefined): string;
encodeFunctionData(functionFragment: 'tierOf', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'getPayerMetrics', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getVendorMetrics', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'processedInvoiceIds', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'recordVerifiedSettlement', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setSettlementVerifier', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'settlementVerifier', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tierOf', data: BytesLike): Result;
  }

  
    export namespace PayerTrustUpdatedEvent {
      export type InputTuple = [payer: AddressLike, invoiceId: BytesLike, settledInvoiceCount: BigNumberish, onTimeSettlementCount: BigNumberish, lateSettlementCount: BigNumberish, totalPaidUsdc: BigNumberish, lastSettledAt: BigNumberish, tier: BigNumberish];
      export type OutputTuple = [payer: string, invoiceId: string, settledInvoiceCount: bigint, onTimeSettlementCount: bigint, lateSettlementCount: bigint, totalPaidUsdc: bigint, lastSettledAt: bigint, tier: bigint];
      export interface OutputObject {payer: string, invoiceId: string, settledInvoiceCount: bigint, onTimeSettlementCount: bigint, lateSettlementCount: bigint, totalPaidUsdc: bigint, lastSettledAt: bigint, tier: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SettlementVerifierUpdatedEvent {
      export type InputTuple = [previousVerifier: AddressLike, newVerifier: AddressLike];
      export type OutputTuple = [previousVerifier: string, newVerifier: string];
      export interface OutputObject {previousVerifier: string, newVerifier: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace VendorActivityUpdatedEvent {
      export type InputTuple = [vendor: AddressLike, invoiceId: BytesLike, settledInvoiceCount: BigNumberish, totalReceivedUsdc: BigNumberish, lastSettledAt: BigNumberish];
      export type OutputTuple = [vendor: string, invoiceId: string, settledInvoiceCount: bigint, totalReceivedUsdc: bigint, lastSettledAt: bigint];
      export interface OutputObject {vendor: string, invoiceId: string, settledInvoiceCount: bigint, totalReceivedUsdc: bigint, lastSettledAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface MaatTrustRegistry extends BaseContract {
    
    connect(runner?: ContractRunner | null): MaatTrustRegistry;
    waitForDeployment(): Promise<this>;

    interface: MaatTrustRegistryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    getPayerMetrics: TypedContractMethod<
      [payer: AddressLike, ],
      [MaatTrustRegistry.PayerMetricsStructOutput],
      'view'
    >
    

    
    getVendorMetrics: TypedContractMethod<
      [vendor: AddressLike, ],
      [MaatTrustRegistry.VendorMetricsStructOutput],
      'view'
    >
    

    
    processedInvoiceIds: TypedContractMethod<
      [arg0: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    recordVerifiedSettlement: TypedContractMethod<
      [invoiceId: BytesLike, payer: AddressLike, vendor: AddressLike, amount: BigNumberish, settledAt: BigNumberish, onTime: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    setSettlementVerifier: TypedContractMethod<
      [newVerifier: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    settlementVerifier: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    tierOf: TypedContractMethod<
      [payer: AddressLike, ],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'getPayerMetrics'): TypedContractMethod<
      [payer: AddressLike, ],
      [MaatTrustRegistry.PayerMetricsStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getVendorMetrics'): TypedContractMethod<
      [vendor: AddressLike, ],
      [MaatTrustRegistry.VendorMetricsStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'processedInvoiceIds'): TypedContractMethod<
      [arg0: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'recordVerifiedSettlement'): TypedContractMethod<
      [invoiceId: BytesLike, payer: AddressLike, vendor: AddressLike, amount: BigNumberish, settledAt: BigNumberish, onTime: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setSettlementVerifier'): TypedContractMethod<
      [newVerifier: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'settlementVerifier'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'tierOf'): TypedContractMethod<
      [payer: AddressLike, ],
      [bigint],
      'view'
    >;

    getEvent(key: 'PayerTrustUpdated'): TypedContractEvent<PayerTrustUpdatedEvent.InputTuple, PayerTrustUpdatedEvent.OutputTuple, PayerTrustUpdatedEvent.OutputObject>;
getEvent(key: 'SettlementVerifierUpdated'): TypedContractEvent<SettlementVerifierUpdatedEvent.InputTuple, SettlementVerifierUpdatedEvent.OutputTuple, SettlementVerifierUpdatedEvent.OutputObject>;
getEvent(key: 'VendorActivityUpdated'): TypedContractEvent<VendorActivityUpdatedEvent.InputTuple, VendorActivityUpdatedEvent.OutputTuple, VendorActivityUpdatedEvent.OutputObject>;

    filters: {
      
      'PayerTrustUpdated(address,bytes32,uint256,uint256,uint256,uint256,uint256,uint8)': TypedContractEvent<PayerTrustUpdatedEvent.InputTuple, PayerTrustUpdatedEvent.OutputTuple, PayerTrustUpdatedEvent.OutputObject>;
      PayerTrustUpdated: TypedContractEvent<PayerTrustUpdatedEvent.InputTuple, PayerTrustUpdatedEvent.OutputTuple, PayerTrustUpdatedEvent.OutputObject>;
    

      'SettlementVerifierUpdated(address,address)': TypedContractEvent<SettlementVerifierUpdatedEvent.InputTuple, SettlementVerifierUpdatedEvent.OutputTuple, SettlementVerifierUpdatedEvent.OutputObject>;
      SettlementVerifierUpdated: TypedContractEvent<SettlementVerifierUpdatedEvent.InputTuple, SettlementVerifierUpdatedEvent.OutputTuple, SettlementVerifierUpdatedEvent.OutputObject>;
    

      'VendorActivityUpdated(address,bytes32,uint256,uint256,uint256)': TypedContractEvent<VendorActivityUpdatedEvent.InputTuple, VendorActivityUpdatedEvent.OutputTuple, VendorActivityUpdatedEvent.OutputObject>;
      VendorActivityUpdated: TypedContractEvent<VendorActivityUpdatedEvent.InputTuple, VendorActivityUpdatedEvent.OutputTuple, VendorActivityUpdatedEvent.OutputObject>;
    
    };
  }