/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace IAttestcoinQueryVerifier {
      
    export type MerkleProofEntryStruct = {hash: BytesLike, isLeft: boolean}

    export type MerkleProofEntryStructOutput = [hash: string, isLeft: boolean] & {hash: string, isLeft: boolean }
  

    export type MerkleProofStruct = {root: BytesLike, siblings: IAttestcoinQueryVerifier.MerkleProofEntryStruct[]}

    export type MerkleProofStructOutput = [root: string, siblings: IAttestcoinQueryVerifier.MerkleProofEntryStructOutput[]] & {root: string, siblings: IAttestcoinQueryVerifier.MerkleProofEntryStructOutput[] }
  

    export type ContinuityProofStruct = {lowerEndpointDigest: BytesLike, roots: BytesLike[]}

    export type ContinuityProofStructOutput = [lowerEndpointDigest: string, roots: string[]] & {lowerEndpointDigest: string, roots: string[] }
  
    }

  export interface IAttestcoinQueryVerifierInterface extends Interface {
    getFunction(nameOrSignature: "calculateTxIndex" | "verify(uint64,uint64[],bytes[],(bytes32,(bytes32,bool)[])[],(bytes32,bytes32[]))" | "verify(uint64,uint64,bytes,(bytes32,(bytes32,bool)[]),(bytes32,bytes32[]))"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'calculateTxIndex', values: [IAttestcoinQueryVerifier.MerkleProofStruct]): string;
encodeFunctionData(functionFragment: 'verify(uint64,uint64[],bytes[],(bytes32,(bytes32,bool)[])[],(bytes32,bytes32[]))', values: [BigNumberish, BigNumberish[], BytesLike[], IAttestcoinQueryVerifier.MerkleProofStruct[], IAttestcoinQueryVerifier.ContinuityProofStruct]): string;
encodeFunctionData(functionFragment: 'verify(uint64,uint64,bytes,(bytes32,(bytes32,bool)[]),(bytes32,bytes32[]))', values: [BigNumberish, BigNumberish, BytesLike, IAttestcoinQueryVerifier.MerkleProofStruct, IAttestcoinQueryVerifier.ContinuityProofStruct]): string;

    decodeFunctionResult(functionFragment: 'calculateTxIndex', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'verify(uint64,uint64[],bytes[],(bytes32,(bytes32,bool)[])[],(bytes32,bytes32[]))', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'verify(uint64,uint64,bytes,(bytes32,(bytes32,bool)[]),(bytes32,bytes32[]))', data: BytesLike): Result;
  }

  

  export interface IAttestcoinQueryVerifier extends BaseContract {
    
    connect(runner?: ContractRunner | null): IAttestcoinQueryVerifier;
    waitForDeployment(): Promise<this>;

    interface: IAttestcoinQueryVerifierInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    calculateTxIndex: TypedContractMethod<
      [merkleProof: IAttestcoinQueryVerifier.MerkleProofStruct, ],
      [bigint],
      'view'
    >
    

    
    "verify(uint64,uint64[],bytes[],(bytes32,(bytes32,bool)[])[],(bytes32,bytes32[]))": TypedContractMethod<
      [chainKey: BigNumberish, heights: BigNumberish[], encodedTransactions: BytesLike[], merkleProofs: IAttestcoinQueryVerifier.MerkleProofStruct[], sharedContinuityProof: IAttestcoinQueryVerifier.ContinuityProofStruct, ],
      [boolean],
      'view'
    >
    

    
    "verify(uint64,uint64,bytes,(bytes32,(bytes32,bool)[]),(bytes32,bytes32[]))": TypedContractMethod<
      [chainKey: BigNumberish, height: BigNumberish, encodedTransaction: BytesLike, merkleProof: IAttestcoinQueryVerifier.MerkleProofStruct, continuityProof: IAttestcoinQueryVerifier.ContinuityProofStruct, ],
      [boolean],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'calculateTxIndex'): TypedContractMethod<
      [merkleProof: IAttestcoinQueryVerifier.MerkleProofStruct, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'verify(uint64,uint64[],bytes[],(bytes32,(bytes32,bool)[])[],(bytes32,bytes32[]))'): TypedContractMethod<
      [chainKey: BigNumberish, heights: BigNumberish[], encodedTransactions: BytesLike[], merkleProofs: IAttestcoinQueryVerifier.MerkleProofStruct[], sharedContinuityProof: IAttestcoinQueryVerifier.ContinuityProofStruct, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'verify(uint64,uint64,bytes,(bytes32,(bytes32,bool)[]),(bytes32,bytes32[]))'): TypedContractMethod<
      [chainKey: BigNumberish, height: BigNumberish, encodedTransaction: BytesLike, merkleProof: IAttestcoinQueryVerifier.MerkleProofStruct, continuityProof: IAttestcoinQueryVerifier.ContinuityProofStruct, ],
      [boolean],
      'view'
    >;

    

    filters: {
      
    };
  }