/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IAttestcoinQueryVerifier, IAttestcoinQueryVerifierInterface } from "../../interfaces/IAttestcoinQueryVerifier.js";

  const _abi = [
  {
    "inputs": [
      {
        "components": [
          {
            "internalType": "bytes32",
            "name": "root",
            "type": "bytes32"
          },
          {
            "components": [
              {
                "internalType": "bytes32",
                "name": "hash",
                "type": "bytes32"
              },
              {
                "internalType": "bool",
                "name": "isLeft",
                "type": "bool"
              }
            ],
            "internalType": "struct IAttestcoinQueryVerifier.MerkleProofEntry[]",
            "name": "siblings",
            "type": "tuple[]"
          }
        ],
        "internalType": "struct IAttestcoinQueryVerifier.MerkleProof",
        "name": "merkleProof",
        "type": "tuple"
      }
    ],
    "name": "calculateTxIndex",
    "outputs": [
      {
        "internalType": "uint64",
        "name": "",
        "type": "uint64"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint64",
        "name": "chainKey",
        "type": "uint64"
      },
      {
        "internalType": "uint64[]",
        "name": "heights",
        "type": "uint64[]"
      },
      {
        "internalType": "bytes[]",
        "name": "encodedTransactions",
        "type": "bytes[]"
      },
      {
        "components": [
          {
            "internalType": "bytes32",
            "name": "root",
            "type": "bytes32"
          },
          {
            "components": [
              {
                "internalType": "bytes32",
                "name": "hash",
                "type": "bytes32"
              },
              {
                "internalType": "bool",
                "name": "isLeft",
                "type": "bool"
              }
            ],
            "internalType": "struct IAttestcoinQueryVerifier.MerkleProofEntry[]",
            "name": "siblings",
            "type": "tuple[]"
          }
        ],
        "internalType": "struct IAttestcoinQueryVerifier.MerkleProof[]",
        "name": "merkleProofs",
        "type": "tuple[]"
      },
      {
        "components": [
          {
            "internalType": "bytes32",
            "name": "lowerEndpointDigest",
            "type": "bytes32"
          },
          {
            "internalType": "bytes32[]",
            "name": "roots",
            "type": "bytes32[]"
          }
        ],
        "internalType": "struct IAttestcoinQueryVerifier.ContinuityProof",
        "name": "sharedContinuityProof",
        "type": "tuple"
      }
    ],
    "name": "verify",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint64",
        "name": "chainKey",
        "type": "uint64"
      },
      {
        "internalType": "uint64",
        "name": "height",
        "type": "uint64"
      },
      {
        "internalType": "bytes",
        "name": "encodedTransaction",
        "type": "bytes"
      },
      {
        "components": [
          {
            "internalType": "bytes32",
            "name": "root",
            "type": "bytes32"
          },
          {
            "components": [
              {
                "internalType": "bytes32",
                "name": "hash",
                "type": "bytes32"
              },
              {
                "internalType": "bool",
                "name": "isLeft",
                "type": "bool"
              }
            ],
            "internalType": "struct IAttestcoinQueryVerifier.MerkleProofEntry[]",
            "name": "siblings",
            "type": "tuple[]"
          }
        ],
        "internalType": "struct IAttestcoinQueryVerifier.MerkleProof",
        "name": "merkleProof",
        "type": "tuple"
      },
      {
        "components": [
          {
            "internalType": "bytes32",
            "name": "lowerEndpointDigest",
            "type": "bytes32"
          },
          {
            "internalType": "bytes32[]",
            "name": "roots",
            "type": "bytes32[]"
          }
        ],
        "internalType": "struct IAttestcoinQueryVerifier.ContinuityProof",
        "name": "continuityProof",
        "type": "tuple"
      }
    ],
    "name": "verify",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class IAttestcoinQueryVerifier__factory {
    static readonly abi = _abi;
    static createInterface(): IAttestcoinQueryVerifierInterface {
      return new Interface(_abi) as IAttestcoinQueryVerifierInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IAttestcoinQueryVerifier {
      return new Contract(address, _abi, runner) as unknown as IAttestcoinQueryVerifier;
    }
  }
  