/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../common.js"
  import type { ExecutionReporter, ExecutionReporterInterface } from "../ExecutionReporter.js";

  const _abi = [
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "agent",
        "type": "address"
      },
      {
        "indexed": true,
        "internalType": "bytes32",
        "name": "executionId",
        "type": "bytes32"
      },
      {
        "indexed": false,
        "internalType": "bool",
        "name": "success",
        "type": "bool"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "volume",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "timestamp",
        "type": "uint256"
      }
    ],
    "name": "AgentExecutionRecorded",
    "type": "event"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "agent",
        "type": "address"
      },
      {
        "internalType": "bytes32",
        "name": "executionId",
        "type": "bytes32"
      },
      {
        "internalType": "bool",
        "name": "success",
        "type": "bool"
      },
      {
        "internalType": "uint256",
        "name": "volume",
        "type": "uint256"
      }
    ],
    "name": "reportExecution",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  const _bytecode = "0x6080806040523460135760c6908160188239f35b5f80fdfe60808060405260043610156011575f80fd5b5f3560e01c63cac23417146023575f80fd5b34608c576080366003190112608c576004356001600160a01b03811690819003608c57604435801515809103608c57825260643560208301524260408301527f44915bb1e68684d23f17d15d1bb9dc990b054898278edfdaf94f26ef35bb18e1606060243593a3005b5f80fdfea2646970667358221220b361651352eac36170ae8141468e399e2f78ec2167c717e2343b3f80ccfca75f64736f6c634300081c0033";

  
      type ExecutionReporterConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: ExecutionReporterConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class ExecutionReporter__factory extends ContractFactory {
    
      constructor(...args: ExecutionReporterConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<ExecutionReporter & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): ExecutionReporter__factory {
      return super.connect(runner) as ExecutionReporter__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): ExecutionReporterInterface {
      return new Interface(_abi) as ExecutionReporterInterface;
    }
    
    override attach(address: string | Addressable): ExecutionReporter {
      return super.attach(address) as ExecutionReporter;
    }
  static connect(address: string, runner?: ContractRunner | null): ExecutionReporter {
      return new Contract(address, _abi, runner) as unknown as ExecutionReporter;
    }
  }

  
  