/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, AddressLike, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../common.js"
  import type { MaatPolicy, MaatPolicyInterface } from "../MaatPolicy.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "maatCoreAddress",
        "type": "address"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "constructor"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "agent",
        "type": "address"
      }
    ],
    "name": "canOperate",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "agent",
        "type": "address"
      }
    ],
    "name": "delegationCap",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "maatCore",
    "outputs": [
      {
        "internalType": "contract MaatCore",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  const _bytecode = "0x60a034607557601f61038c38819003918201601f19168301916001600160401b03831184841017607957808492602094604052833981010312607557516001600160a01b038116908190036075576080526040516102fe908161008e823960805181818160800152818161018101526102280152f35b5f80fd5b634e487b7160e01b5f52604160045260245ffdfe6080806040526004361015610012575f80fd5b5f3560e01c9081633fef8bf71461016f57508063ad1738f5146101385763eb56a7961461003d575f80fd5b34610134576020366003190112610134576004356001600160a01b038116908190036101345760405163191ee97760e31b815260048101919091526020816024817f00000000000000000000000000000000000000000000000000000000000000006001600160a01b03165afa908115610129575f916100fa575b5060058110156100e65780602091151590816100da575b506040519015158152f35b6004915014155f6100cf565b634e487b7160e01b5f52602160045260245ffd5b61011c915060203d602011610122575b61011481836101b0565b8101906101e6565b5f6100b8565b503d61010a565b6040513d5f823e3d90fd5b5f80fd5b34610134576020366003190112610134576004356001600160a01b0381168103610134576101676020916101fe565b604051908152f35b34610134575f366003190112610134577f00000000000000000000000000000000000000000000000000000000000000006001600160a01b03168152602090f35b90601f8019910116810190811067ffffffffffffffff8211176101d257604052565b634e487b7160e01b5f52604160045260245ffd5b90816020910312610134575160058110156101345790565b60405163191ee97760e31b81526001600160a01b03918216600482015290602090829060249082907f0000000000000000000000000000000000000000000000000000000000000000165afa908115610129575f916102a9575b5060058110156100e6576003811461029a576002811461028b5760011461027d575f90565b690a968163f0a57b40000090565b506934f086f3b33b6840000090565b5069d3c21bcecceda100000090565b6102c2915060203d6020116101225761011481836101b0565b5f61025856fea2646970667358221220e7616b73ceca3bd83eaddc45a88fdc7faa4685dfc65cd32e8b3a8162c5b8411a64736f6c634300081c0033";

  
      type MaatPolicyConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: MaatPolicyConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class MaatPolicy__factory extends ContractFactory {
    
      constructor(...args: MaatPolicyConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(maatCoreAddress: AddressLike, overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(maatCoreAddress, overrides || {});
    };
    override deploy(maatCoreAddress: AddressLike, overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(maatCoreAddress, overrides || {}) as Promise<MaatPolicy & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): MaatPolicy__factory {
      return super.connect(runner) as MaatPolicy__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): MaatPolicyInterface {
      return new Interface(_abi) as MaatPolicyInterface;
    }
    
    override attach(address: string | Addressable): MaatPolicy {
      return super.attach(address) as MaatPolicy;
    }
  static connect(address: string, runner?: ContractRunner | null): MaatPolicy {
      return new Contract(address, _abi, runner) as unknown as MaatPolicy;
    }
  }

  
  