/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, AddressLike, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../common.js"
  import type { MaatCreditPolicy, MaatCreditPolicyInterface } from "../MaatCreditPolicy.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "trustRegistryAddress",
        "type": "address"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "constructor"
  },
  {
    "inputs": [],
    "name": "InvalidTrustRegistry",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "BRONZE_LIMIT_USDC",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "GOLD_LIMIT_USDC",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "SILVER_LIMIT_USDC",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "payer",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "invoiceAmount",
        "type": "uint256"
      }
    ],
    "name": "canExtendTerms",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "payer",
        "type": "address"
      }
    ],
    "name": "creditLimitUsdc",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "trustRegistry",
    "outputs": [
      {
        "internalType": "contract MaatTrustRegistry",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  const _bytecode = "0x60a034608257601f61037938819003918201601f19168301916001600160401b03831184841017608657808492602094604052833981010312608257516001600160a01b0381169081900360825780156073576080526040516102de908161009b823960805181818160de01526101b30152f35b63bd7ea49560e01b5f5260045ffd5b5f80fd5b634e487b7160e01b5f52604160045260245ffdfe6080806040526004361015610012575f80fd5b5f3560e01c9081632116b7a6146101565750806327ac2cf41461012b5780634fd1724c1461010d5780639b835427146100c9578063df83101a146100aa5763eee4a6771461005e575f80fd5b346100a65760403660031901126100a6576020610079610173565b6024358015159182610092575b50506040519015158152f35b61009d919250610189565b10155f80610086565b5f80fd5b346100a6575f3660031901126100a65760206040516402540be4008152f35b346100a6575f3660031901126100a6576040517f00000000000000000000000000000000000000000000000000000000000000006001600160a01b03168152602090f35b346100a6575f3660031901126100a6576020604051633b9aca008152f35b346100a65760203660031901126100a657602061014e610149610173565b610189565b604051908152f35b346100a6575f3660031901126100a65780640ba43b740060209252f35b600435906001600160a01b03821682036100a657565b60405163191ee97760e31b81526001600160a01b03918216600482015290602090829060249082907f0000000000000000000000000000000000000000000000000000000000000000165afa90811561029d575f91610238575b506005811015610224576003811461021a576002811461021057600114610208575f90565b633b9aca0090565b506402540be40090565b50640ba43b740090565b634e487b7160e01b5f52602160045260245ffd5b905060203d602011610296575b601f8101601f1916820167ffffffffffffffff811183821017610282576020918391604052810103126100a6575160058110156100a6575f6101e3565b634e487b7160e01b5f52604160045260245ffd5b503d610245565b6040513d5f823e3d90fdfea2646970667358221220d1ca46a10fb9b1534d264356b14b17327e2aad03a6d7ed05dadfe42d19ad260764736f6c634300081c0033";

  
      type MaatCreditPolicyConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: MaatCreditPolicyConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class MaatCreditPolicy__factory extends ContractFactory {
    
      constructor(...args: MaatCreditPolicyConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(trustRegistryAddress: AddressLike, overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(trustRegistryAddress, overrides || {});
    };
    override deploy(trustRegistryAddress: AddressLike, overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(trustRegistryAddress, overrides || {}) as Promise<MaatCreditPolicy & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): MaatCreditPolicy__factory {
      return super.connect(runner) as MaatCreditPolicy__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): MaatCreditPolicyInterface {
      return new Interface(_abi) as MaatCreditPolicyInterface;
    }
    
    override attach(address: string | Addressable): MaatCreditPolicy {
      return super.attach(address) as MaatCreditPolicy;
    }
  static connect(address: string, runner?: ContractRunner | null): MaatCreditPolicy {
      return new Contract(address, _abi, runner) as unknown as MaatCreditPolicy;
    }
  }

  
  