/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace INativeQueryVerifier {
      
    export type MerkleProofEntryStruct = {hash: BytesLike, isLeft: boolean}

    export type MerkleProofEntryStructOutput = [hash: string, isLeft: boolean] & {hash: string, isLeft: boolean }
  

    export type MerkleProofStruct = {root: BytesLike, siblings: INativeQueryVerifier.MerkleProofEntryStruct[]}

    export type MerkleProofStructOutput = [root: string, siblings: INativeQueryVerifier.MerkleProofEntryStructOutput[]] & {root: string, siblings: INativeQueryVerifier.MerkleProofEntryStructOutput[] }
  

    export type ContinuityProofStruct = {lowerEndpointDigest: BytesLike, roots: BytesLike[]}

    export type ContinuityProofStructOutput = [lowerEndpointDigest: string, roots: string[]] & {lowerEndpointDigest: string, roots: string[] }
  
    }

  export interface MaatVerifierInterface extends Interface {
    getFunction(nameOrSignature: "VERIFIER" | "maatCore" | "processedQueries" | "sourceChainKey" | "sourceReporter" | "submitVerifiedExecution"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ExecutionProofAccepted"): EventFragment;

    encodeFunctionData(functionFragment: 'VERIFIER', values?: undefined): string;
encodeFunctionData(functionFragment: 'maatCore', values?: undefined): string;
encodeFunctionData(functionFragment: 'processedQueries', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'sourceChainKey', values?: undefined): string;
encodeFunctionData(functionFragment: 'sourceReporter', values?: undefined): string;
encodeFunctionData(functionFragment: 'submitVerifiedExecution', values: [BigNumberish, BigNumberish, BytesLike, INativeQueryVerifier.MerkleProofStruct, INativeQueryVerifier.ContinuityProofStruct]): string;

    decodeFunctionResult(functionFragment: 'VERIFIER', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'maatCore', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'processedQueries', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'sourceChainKey', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'sourceReporter', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'submitVerifiedExecution', data: BytesLike): Result;
  }

  
    export namespace ExecutionProofAcceptedEvent {
      export type InputTuple = [chainKey: BigNumberish, height: BigNumberish, txIndex: BigNumberish, agent: AddressLike, executionId: BytesLike];
      export type OutputTuple = [chainKey: bigint, height: bigint, txIndex: bigint, agent: string, executionId: string];
      export interface OutputObject {chainKey: bigint, height: bigint, txIndex: bigint, agent: string, executionId: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface MaatVerifier extends BaseContract {
    
    connect(runner?: ContractRunner | null): MaatVerifier;
    waitForDeployment(): Promise<this>;

    interface: MaatVerifierInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    VERIFIER: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    maatCore: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    processedQueries: TypedContractMethod<
      [arg0: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    sourceChainKey: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    sourceReporter: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    submitVerifiedExecution: TypedContractMethod<
      [chainKey: BigNumberish, height: BigNumberish, encodedTransaction: BytesLike, merkleProof: INativeQueryVerifier.MerkleProofStruct, continuityProof: INativeQueryVerifier.ContinuityProofStruct, ],
      [boolean],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'VERIFIER'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'maatCore'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'processedQueries'): TypedContractMethod<
      [arg0: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'sourceChainKey'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'sourceReporter'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'submitVerifiedExecution'): TypedContractMethod<
      [chainKey: BigNumberish, height: BigNumberish, encodedTransaction: BytesLike, merkleProof: INativeQueryVerifier.MerkleProofStruct, continuityProof: INativeQueryVerifier.ContinuityProofStruct, ],
      [boolean],
      'nonpayable'
    >;

    getEvent(key: 'ExecutionProofAccepted'): TypedContractEvent<ExecutionProofAcceptedEvent.InputTuple, ExecutionProofAcceptedEvent.OutputTuple, ExecutionProofAcceptedEvent.OutputObject>;

    filters: {
      
      'ExecutionProofAccepted(uint64,uint64,uint64,address,bytes32)': TypedContractEvent<ExecutionProofAcceptedEvent.InputTuple, ExecutionProofAcceptedEvent.OutputTuple, ExecutionProofAcceptedEvent.OutputObject>;
      ExecutionProofAccepted: TypedContractEvent<ExecutionProofAcceptedEvent.InputTuple, ExecutionProofAcceptedEvent.OutputTuple, ExecutionProofAcceptedEvent.OutputObject>;
    
    };
  }