/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BytesLike, FunctionFragment, Result, Interface, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface AttestedPaymentDiagnosticHarnessInterface extends Interface {
    getFunction(nameOrSignature: "decodeCommon" | "decodeEnvelope" | "decodeReceipt"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'decodeCommon', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'decodeEnvelope', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'decodeReceipt', values: [BytesLike]): string;

    decodeFunctionResult(functionFragment: 'decodeCommon', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'decodeEnvelope', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'decodeReceipt', data: BytesLike): Result;
  }

  

  export interface AttestedPaymentDiagnosticHarness extends BaseContract {
    
    connect(runner?: ContractRunner | null): AttestedPaymentDiagnosticHarness;
    waitForDeployment(): Promise<this>;

    interface: AttestedPaymentDiagnosticHarnessInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    decodeCommon: TypedContractMethod<
      [commonChunk: BytesLike, ],
      [[string, boolean, string, bigint] & {sender: string, toIsNull: boolean, destination: string, dataLength: bigint }],
      'view'
    >
    

    
    decodeEnvelope: TypedContractMethod<
      [encodedTransaction: BytesLike, ],
      [[bigint, bigint, string, string] & {txType: bigint, chunkCount: bigint, common: string, receipt: string }],
      'view'
    >
    

    
    decodeReceipt: TypedContractMethod<
      [receiptChunk: BytesLike, ],
      [[bigint, bigint, bigint, bigint] & {status: bigint, gasUsed: bigint, logCount: bigint, bloomLength: bigint }],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'decodeCommon'): TypedContractMethod<
      [commonChunk: BytesLike, ],
      [[string, boolean, string, bigint] & {sender: string, toIsNull: boolean, destination: string, dataLength: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'decodeEnvelope'): TypedContractMethod<
      [encodedTransaction: BytesLike, ],
      [[bigint, bigint, string, string] & {txType: bigint, chunkCount: bigint, common: string, receipt: string }],
      'view'
    >;
getFunction(nameOrSignature: 'decodeReceipt'): TypedContractMethod<
      [receiptChunk: BytesLike, ],
      [[bigint, bigint, bigint, bigint] & {status: bigint, gasUsed: bigint, logCount: bigint, bloomLength: bigint }],
      'view'
    >;

    

    filters: {
      
    };
  }