/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface AttestedPaymentDecoderHarnessInterface extends Interface {
    getFunction(nameOrSignature: "decodePayment"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'decodePayment', values: [BytesLike, AddressLike]): string;

    decodeFunctionResult(functionFragment: 'decodePayment', data: BytesLike): Result;
  }

  

  export interface AttestedPaymentDecoderHarness extends BaseContract {
    
    connect(runner?: ContractRunner | null): AttestedPaymentDecoderHarness;
    waitForDeployment(): Promise<this>;

    interface: AttestedPaymentDecoderHarnessInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    decodePayment: TypedContractMethod<
      [encodedTransaction: BytesLike, sourceRouter: AddressLike, ],
      [[string, string, string, bigint, bigint] & {invoiceId: string, payer: string, vendor: string, amount: bigint, paidAt: bigint }],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'decodePayment'): TypedContractMethod<
      [encodedTransaction: BytesLike, sourceRouter: AddressLike, ],
      [[string, string, string, bigint, bigint] & {invoiceId: string, payer: string, vendor: string, amount: bigint, paidAt: bigint }],
      'view'
    >;

    

    filters: {
      
    };
  }